[site]
title = "andante"
description = "個人的な日記です"
host = "ofni.necocen.info"
about = """
物理学・数学・哲学に関心がある（けれどもそれほど勉強しているわけではない）ソフトウェアエンジニアの日記です。このサイト自身はRustで書かれています。


“andante”という名前は、「歩くような速さで」とよく訳される演奏記号からとっています。日記とは日々を記すものであり、それがどんな日々であるか考えたとき、「歩くような速さで」という言葉が気に入ったのでこの名前にしています。

あまり多くの人が読んでいないような気持ちで書いています。コメント欄はありませんが、何か連絡したいことがあればTwitterなどを利用してください。\
"""

[mathjax]
options = """
{}
"""

[[site.links]]
name = "twitter"
url = "https://twitter.com/necocen"
active = true

[[site.links]]
name = "twitter log"
url = "https://logt.necocen.info/"
active = true

[[site.links]]
name = "read"
url = "https://bookmeter.com/u/27151"
active = true

[[site.links]]
name = "d.hatena"
url = "https://necocen.hatenadiary.org/"
active = false

[author]
name = "κねこせん"
email = "necocen@gmail.com"
