[site]
title = "andante"
description = "個人的な日記です"
host = "ofni.necocen.info"
about = """
ここを編集する必要って実はぜんぜんないと思ったので（ほぼしたことないし）。
"""

[mathjax]
options = """
{}
"""

[[site.links]]
name = "twitter"
url = "https://twitter.com/necocen"
active = true

[[site.links]]
name = "twitter log"
url = "https://logt.necocen.info/"
active = true

[[site.links]]
name = "read"
url = "https://bookmeter.com/u/27151"
active = true

[[site.links]]
name = "d.hatena"
url = "https://necocen.hatenadiary.org/"
active = false

[author]
name = "κねこせん"
email = "necocen@gmail.com"
