// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct Article {
    pub id: i32,
    pub title: String,
    pub text: String,
    pub is_commentable: i32,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}
