[package]
name = "server"
version = "11.0.0"
authors = ["necocen <necocen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
infrastructure = { path = "../infrastructure" }
url = "^2"
tokio = { version = "^1", features = ["full"] }
actix-web = "^4.0.0-beta.5"
actix-files = "^0.6.0-beta.3"
actix-cors = "^0.6.0-beta.1"
askama = { version = "^0.10.5", features = ["mime", "mime_guess"] }
askama_escape = "^0.10.1"
anyhow = "^1.0.40"
bytes = "^1.0"
thiserror = "^1.0.23"
chrono = { version = "^0.4.19", features = ["serde"] }
regex = "^1.4.5"
serde = "^1"
