// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use super::schema::posts;
use chrono::{offset::Utc, TimeZone};
use chrono::{DateTime, NaiveDateTime};
use domain::entities::{Post as PostEntity, PostId};

#[derive(Queryable, Insertable, Debug, Clone)]
pub(crate) struct Post {
    pub id: i32,
    pub title: String,
    pub body: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl From<Post> for PostEntity {
    fn from(post: Post) -> PostEntity {
        PostEntity::new(
            PostId(post.id),
            post.title,
            post.body,
            post.created_at,
            post.updated_at,
        )
    }
}
