[package]
name = "infrastructure"
version = "0.0.0"
authors = ["necocen <necocen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
anyhow = "1.0.56"
diesel = { version = "1.4.8", features = ["postgres", "chrono", "r2d2"] }
r2d2 = "0.8.9"
domain = { path = "../domain" }
elasticsearch = "7.14.0-alpha.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
async-trait = "0.1.52"
url = "2.2.2"
log = "0.4.15"
env_logger = "0.9.0"
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
tokio = { version = "1.17.0", features = ["full"] }
config = { version = "0.12.0", default-features = false, features = ["toml"] }
reqwest = { version = "0.11.10", features = ["json", "rustls-tls"] }

[dev-dependencies]
uuid = { version = "0.8.2", features = ["v4"] }
pretty_assertions = "1.2.0"
assert_matches = "1.5.0"
