[package]
name = "infrastructure"
version = "0.0.0"
authors = ["necocen <necocen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "^0.4.19", features = ["serde"] }
anyhow = "^1.0.40"
diesel = { version = "^1.4.6", features = ["mysql", "postgres", "chrono", "r2d2"] }
r2d2 = "^0.8.9"
domain = { path = "../domain" }
elasticsearch = "7.10.1-alpha.1"
serde = "^1"
serde_json = "^1"
async-trait = "^0.1.42"
url = "^2"
log = "^0.4.14"
