---
name: Build image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      REPOSITORY: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ap-northeast-1.amazonaws.com/nocturne
      ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/PushNocturne
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ env.ROLE }}
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REPOSITORY }}
      - uses: docker/setup-buildx-action@v3
      - shell: bash
        run: echo "${{ secrets.GOOGLE_CLIENT_ID }}"
      - uses: docker/build-push-action@v5
        with:
          context: . # これを指定しないと.gitが含まれないらしい cf. https://github.com/docker/build-push-action?tab=readme-ov-file#git-context
          target: server
          secret-envs: |
            VITE_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          push: true
          tags: |
            ${{ env.REPOSITORY }}:latest
            ${{ env.REPOSITORY }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
